#!/bin/sh
set -eu
THIS_PROJECT_DIR=`git rev-parse --show-toplevel`

format() {
    echo "~~~ Start Code Format In $THIS_PROJECT_DIR"
    # todo::need only format cpp files in stage
    for f in $(find $THIS_PROJECT_DIR -name '*.h' -or -name '*.c' -or -name '*.cpp'); do 
        echo "format ${f}"
        clang-format -style=google -sort-includes=true -i ${f}
    done
    echo "~~~ Code Format Done ~~~"
}

format
